image: node:10

stages:
    - build
    - deploy

build:
    stage: build

    script:
        - npm i
        - npm run build

    artifacts:
        paths:
            - public

# pages:
#     stage: deploy

#     artifacts:
#         paths:
#             - public

#     only:
#         - production

deploy:netlify:
    stage: deploy

    only:
        - production

    script:
        - npm i -g netlify-cli
        - netlify deploy -s $NETLIFY_SITE_ID -p public -t $NETLIFY_ACCESS_TOKEN -e production


