image: node:10

stages:
    - build
    - deploy

cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
        - node_modules/

before_script:
    - npm i

build:
    stage: build

    script:
        - npm i
        - npm run build

    artifacts:
        paths:
            - dist

deploy:netlify:
    stage: deploy

    only:
        - production

    script:
        - npm i -g netlify-cli
        - netlify deploy --prod --dir "dist" --message "${CI_COMMIT_TITLE}"


