language: node_js
node_js:
    - node

script: npm run build

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    repo: wryk/wryk.github.io
    target_branch: master
    on:
        branch: release
