[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "no-referrer"
    X-Clacks-Overhead = "GNU Natalie Nguyen"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[[redirects]]
  from = "https://mystifying-bell-f3a5a1.netlify.com/*"
  to = "https://wryk.moe/:splat"
  status = 301
  force = true